name: ktlint

on:
  pull_request:
    paths:
      - "**/*.kt"
      - ".github/workflows/ktlint.yml"

jobs:
   ktlint:
     runs-on: ubuntu-latest

     steps:
       - name: "checkout"
         uses: actions/checkout@v2

       - name: "ktlint"
         uses: "vroy/gha-kotlin-linter@v1"
       
       - uses: stefanzweifel/git-auto-commit-action@v4
         with:
          commit_message: Apply klint changes
