name: reviewdog
on: [pull_request]
jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: ktlint
        uses: ScaCap/action-ktlint@master
        
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
         github_token: ${{ secrets.github_token }}
         commit_message: Apply klint changes
